### ISSUE TITLE
Add travis and code coverage

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle-s3-adapter#6]
This repo is missing a .travis.yml so its tests don't run in travis - an omission?

Also, add code coverage.

See example in https://github.com/juttle/juttle-elastic-adapter
Once added, review the coverage report to see where we have holes in unit tests, and create issue to add missing tests if any.

**Comment by demmer** [comment]
Assigning to @davidvgalbraith so we can get some test coverage on the adapter.
